version: 2.1

executors:
  windows-executor:
    machine: true  # Use CircleCI's Windows machine executor
    working_directory: C:/repo  # Define working directory (Windows-style path)

jobs:
  install:
    executor: windows-executor
    steps:
      - checkout  # Check out the code
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            venv\Scripts\activate  # Activate virtual environment on Windows
            pip install --upgrade pip
            pip install -r requirements.txt

  test:
    executor: windows-executor
    steps:
      - checkout  # Check out the code
      - run:
          name: List contents of src folder (Debugging step)
          command: dir src  # List files in the src directory (Windows command)
      - run:
          name: Run Tests in src folder
          command: |
            venv\Scripts\activate  # Activate virtual environment on Windows
            pytest src/test.py --maxfail=10 --disable-warnings -v  # Run tests with verbosity

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install





