version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8  # Use Python Docker image
    working_directory: ~/repo  # Set the working directory to the root of the repo
    steps:
      - checkout  # Checkout the code from GitHub repository

      # Step to set the PYTHONPATH to include the root directory of the repo (where main.py is located)
      - run:
          name: Set PYTHONPATH
          command: |
            echo "export PYTHONPATH=$PYTHONPATH:$(pwd)" >> $BASH_ENV  # Add current directory to PYTHONPATH
            source $BASH_ENV  # Ensure the environment variable is loaded

      # Install dependencies from requirements.txt
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Create a virtual environment
            . venv/bin/activate  # Activate the virtual environment
            pip install --upgrade pip  # Upgrade pip
            pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Run tests using pytest in src/test.py
      - run:
          name: Run tests with pytest
          command: |
            . venv/bin/activate  # Activate virtual environment
            pytest src/test.py  # Run the tests located in src/test.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - test









