version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo

jobs:
  install:
    executor: python-executor
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate  # On Windows: venv\Scripts\activate
            pip install --upgrade pip
            pip install -r requirements.txt

  test:
    executor: python-executor
    steps:
      - checkout  
      - run:
          name: Run Tests in src folder
          command: |
            . venv/bin/activate  # On Windows: venv\Scripts\activate
            pytest src/test.py --maxfail=5 --disable-warnings -v  # Run tests from src/test.py

workflows:
  version: 2
  test:
    jobs:
      - install
      - test:
          requires:
            - install



